### ISSUE TITLE
[Bug Report]: plugin crashes on Startup

### ISSUE THREAD

**Issue by Rosstail** [Crazy-Crew/CrazyEnvoys#104]
### Spark link

https://mclo.gs/Wf86vqc

### Server Version

1.19.4

### Server Platform

Paper

### Describe the bug

Got an error on startup since I have updated to the most recent versions of CrazyEnvoys. Logs available on Spark link.
[Spark link](https://mclo.gs/Wf86vqc)

### Steps to reproduce

Install crazyenvoys.
Start the server.

### Additional context

I have tested restarting without CMI and ViaVersion, same results)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by RyderBelserion** [comment]
You have to use 1.20 for this version of CrazyEnvoys.

**Comment by Rosstail** [comment]
Alwright, I will stay on 1.4.20.7 until my server updates to 1.20
