### ISSUE TITLE
%crazyenvoys_crates_time% dose not work!

### ISSUE THREAD

**Issue by MaxPax1234** [Crazy-Crew/CrazyEnvoys#105]
### Server Version

1.19.4

### Server Platform

Spigot

### Describe the bug

i use holographic displays and the placeholder that is suppose to display time before people can open a crate doesn't work. My server is on 1.19.4

### Steps to reproduce

i dont understand this part 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by RyderBelserion** [comment]
You must use DecentHolograms as we no longer support HolographicDisplays. The plugin ( HolographicDisplays ) is also practically abandoned or in maintenance mode.
