### ISSUE TITLE
[Bug Report]: Crates Destroy Snow

### ISSUE THREAD

**Issue by bobhenl** [Crazy-Crew/CrazyEnvoys#124]
### Server Version

1.20.1

### Server Platform

Purpur

### Describe the bug

Hello, crates spawned by crazyenvoys destroy snow on the ground... I guess it should be returned after the envoy is took, or spawned above it?

### Steps to reproduce

Put snow in the region where the envoys are spawning.
Then start envoy.
You'll see ethat envoy replaces snow, which isn't good when you have snowy map.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
https://github.com/Crazy-Crew/CrazyEnvoys/issues/117
