### ISSUE TITLE
[Getting the same Items over and over]: 

### ISSUE THREAD

**Issue by AdamDAuria** [Crazy-Crew/CrazyEnvoys#126]
### Server Version

1.20.4

### Server Platform

Paper

### Describe the bug

Getting the same items over and over again idk if this is because i don't have many drops like only 5 drops only i have all items 100% drop chance all the time and have 23 items and idk if i'm follow the right format right or i'm missing something

**The yml file:**

Settings:
  # If they need a permission to claim this envoy. Set too false to disable.
  Claim-Permission: false
  # What permission they need.
  Claim-Permission-Name: 'lucky.envoy.use'
  Prize-Message:
    - '&7You have won &c{reward} &7from &c{tier}.'
  Spawn-Chance: 100
  Use-Chance: true
  Placed-Block: 'ENDER_CHEST'
  Bulk-Prizes:
    Toggle: false
    Random: true
    Max-Bulk: 21
  Hologram-Toggle: true
  Hologram-Height: 1.5
  Hologram-Range: 8
  Hologram: #Requires 3rd party plugins such as DecentHolograms to function. https://github.com/Crazy-Crew/CrazyEnvoys/blob/main/platforms/paper/src/main/java/com/badbones69/crazyenvoys/support/libraries/PluginSupport.java
    # %crazyenvoys_crates_time% shows the grace period of the envoy if the option in config.yml called Crate-Countdown.Toggle is enabled.
    - '&7&l(&e&l!&7&l) &e&lLucky Crate'
    - '%crazyenvoys_crates_time%'
  Firework-Toggle: false
  Firework-Colors:
    - 'Gray'
    - 'Black'
    - 'Yellow'
  Signal-Flare:
    Toggle: false
    Time: '25s'
    Colors:
      - 'Gray'
      - 'Black'
      - 'Yellow'
###################################
#             Items: Options
# Item:<ID:MD> - You can choose the item with its id and meta data.
# Amount:<Number> - Choose how many of the item you get.
# Name:<Name> - The display name that goes on the item.
# Lore:<Line 1>,<Line 2>,<Line 3>,<Line 4> - The lore that will go under the enchantments. Split lines with a ','
# Glowing:<True/False> - Will make the item have a glowing effect without having an enchantment on the item. (Only supports 1.8 - 1.11)
# Unbreakable-Item:<True/False> - Will add the Unbreaking NBT tag to the item to allow custom textured items to be gained through the envoys.
# <Enchantment>:<Level> - Choose the enchantment you want to add to the item. You can use the in-game names of the enchantment if you want. Replace the spaces in the name with "_".
###################################
Prizes:
  '1': #Prize number
    DisplayName: '&aShulkerbox' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won a &ashulkerbox&7.'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% shulker_box 1'
      
  '2': #Prize number
    DisplayName: '&a1 wither skull' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won a &awither_skull&7.'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% wither_skeleton_skull 1'
      
  '3': #Prize number
    DisplayName: '&a$3 Dollers' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a$3&7.'
    Commands: #The commands that will be run when this prize is won.
      - 'economy give %player% 3'
      
  '4': #Prize number
    DisplayName: '&a$4 Dollers' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a$4&7.'
    Commands: #The commands that will be run when this prize is won.
      - 'economy give %player% 4'
      
  '5': #Prize number
    DisplayName: '&a3 netherite ingots' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a3 Netherite Ingots&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% netherite_ingot 3'
      
  '6': #Prize number
    DisplayName: '&aBeacon' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a Beacon&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% beacon 1'
      
  '7': #Prize number
    DisplayName: '&aElytra' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a elytra&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% elytra 1'
      
  '8': #Prize number
    DisplayName: '&a1 Diamond Block' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a diamondblock&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% diamond_block 1'
      
  '9': #Prize number
    DisplayName: '&aNether star' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a nether_star&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% nether_star 1'
      
  '10': #Prize number
    DisplayName: '&aMending Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a mending book&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 mending'
      
  '11': #Prize number
    DisplayName: '&ainfinity Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a infinity book&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 infinity'
      
  '12': #Prize number
    DisplayName: '&apower 5 Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a power 5 book&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 power'
      
  '13': #Prize number
    DisplayName: '&aunbreaking 3 Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a unbreaking 3 book&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 unbreaking'
      
  '14': #Prize number
    DisplayName: '&aefficiency 5 Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a Efficiency 5 book&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 Efficiency'
      
  '15': #Prize number
    DisplayName: '&afortune 3 Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a Fortune 3 book&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 Fortune'
      
  '16': #Prize number
    DisplayName: '&aSharpness 5 Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a sharpness 5 book&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 sharpness'
      
  '17': #Prize number
    DisplayName: '&afireprotection 4 Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a fireprotection 4 book&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 fire_protection'
      
  '18': #Prize number
    DisplayName: '&asilktounch  Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a silk_Touch book&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 silk_touch'
      
  '19': #Prize number
    DisplayName: '&aprotection 5  Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a protection 5&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 protection'
      
  '20': #Prize number
    DisplayName: '&ablast protection 5  Book' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a blast protection 5&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_book 1 blast_protection'
      
  '21': #Prize number
    DisplayName: '&aenchanted golden apple' #The display name used in {reward}
    Chance: 100 #The chance that it will be won.
    Drop-Items: false #Drop all items in the Items: option on the ground instead of into their inventory.
    Messages: #The message that will be sent to the player if won.
      - '&7You have just won &a enchanted golden apple&7'
    Commands: #The commands that will be run when this prize is won.
      - 'give %player% enchanted_golden_apple 1'
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      

### Crate Type

None

### Steps to reproduce

NA

### Additional context

idk if i'm follow the right format right

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
This isn't a bug, This is a chance system works.... 100 out of 100 means the first prize that matches 100 out of 100 is picked and then the loop is cancelled thus getting the same prize every time.

You can't use the chance system in CrazyCrates like this.
