### ISSUE TITLE
CrazyEnvoy flare glowing

### ISSUE THREAD

**Issue by AlFr3on111** [Crazy-Crew/CrazyEnvoys#142]
### Describe the feature

option to make the flare item could glow like enchanted item or enchanted book
i use 1.20.6 purpur

exmaple:
glow: true // this option make the flare item glow

### Other

its simple feature i have no screenshot or something for it

**Comment by ryderbelserion** [comment]
Added in [56de4de](https://github.com/Crazy-Crew/CrazyEnvoys/commit/56de4de6d5e9d3429f4970250b0e5298c34fff3e)
