### ISSUE TITLE
[Bug Report] PDC is not available in 1.12.2

### ISSUE THREAD

**Issue by Sliman4** [Crazy-Crew/CrazyEnvoys#74]
**Describe the bug**
It spams the console with errors when right-clicking a chest, or just every second or so. I believe it's caused by 1a82d79. PDC was added in 1.14 or 1.15 if I remember correctly, not in 1.11.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.12.2
 - Plugin Version: legacy branch (1a82d79)

*Do **NOT** say Latest use `/version crazyenvoy` in the console.

**Pastebin any errors in console**
Link: https://mclo.gs/LcJnWHs

**Issue**

**Screenshots**

**Comment by RyderBelserion** [comment]
Fixed in these commits on the legacy branch.

![image](https://user-images.githubusercontent.com/52214219/199246708-3024ae97-4d42-464e-b7f5-14b1e616b6ae.png)
