### ISSUE TITLE
[Bug Report]: 1.4.20.4

### ISSUE THREAD

**Issue by Studio755** [Crazy-Crew/CrazyEnvoys#93]
### Server Version

1.19.3

### Server Platform

Paper

### Describe the bug

i have a world guard region in my survival world where the drops will spawn and a little platform and when i start a envoy it does not drop on it for some reason it works in the open tho.

### Steps to reproduce

Make a world gaurd region with block-place deny and block-break deny and put a envoy on it.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by RyderBelserion** [comment]
https://github.com/Crazy-Crew/CrazyEnvoys/issues/99
