### ISSUE TITLE
[Bug Report]: 1.17.1 / Paper / Not work Data.yml

### ISSUE THREAD

**Issue by kurkinsnetwork** [Crazy-Crew/CrazyEnvoys#98]
### Server Version

1.16.5

### Server Platform

Paper

### Describe the bug

when i edit and save spawn location and /envoy start its says spawn point not found. help us please

### Steps to reproduce

Download and open 1.17.1 Paper server
download crazyenvoys
edit crate location
save location
/envoy start
......... but never starting envoy

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by kurkinsnetwork** [comment]
how can i fix it

**Comment by RyderBelserion** [comment]
**We do not update for older versions anymore nor do we support staying on older versions as older versions do lack bug fixes, improvements.**

If you join the `Discord`, You can search through the `#crazy-envoys` channel which has multiple conversations on how to make it work but `this system will be changing in the newer versions` to be easier to use.

You have to toggle and mess with options in the `config.yml` until it works.
