### ISSUE TITLE
[Bug Report]: Envoys not being able to spawn in WorldGuard region with block-place deny

### ISSUE THREAD

**Issue by PopFizzCode** [Crazy-Crew/CrazyEnvoys#99]
### Spark link

This doenst need a spark report

### Server Version

1.19.3

### Server Platform

Paper

### Describe the bug

hey, there's this bug on the latest version: https://youtu.be/VsCwxdF7J-c
no errors in console (even when the plugin it's loading)

server version is 1.19.4 (it isnt available in the menu on github) and plugin version is CrazyEnvoys 1.4.20.4

the issue is that with block-place deny it cant place the envoys, but I cant let them place blocks in my spawn so you should make a worldguard integration, is that possible? thanks in advance

### Steps to reproduce

https://youtu.be/VsCwxdF7J-c

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by RyderBelserion** [comment]
https://worldguard.enginehub.org/en/latest/regions/flags/

![image](https://github.com/Crazy-Crew/CrazyEnvoys/assets/52214219/80adbb95-f623-4db9-9a07-b30091a88853)

It's related to WorldGuard changes which is why Envoys sometimes won't spawn.
